apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  RAILS_SERVE_STATIC_FILES: "true"
  SOLR_URL: http://umedia-solr-ip-service:8983/solr/core
  REDIS_URL: redis://umedia-redis-ip-service:6379
  REDIS_CACHE_URL: redis://umedia-redis-cache-ip-service:6380
  RAILS_ENV: production
  NODE_ENV: production
  UMEDIA_SEARCH_ROWS: "20"
  PARHELION_CDM_ENDPOINT: https://cdm16022.contentdm.oclc.org
  UMEDIA_COLLECTION_PAGE_LIMIT: "5"
  SOLR_BACKUP_LOCATION: /solr_snapshots